name: build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest 
    env:
      Solution_Name: volume-utility.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: ビルド(NuGetパッケージ復元あり)
      run: |
        msbuild -t:restore
        msbuild ${{env.Solution_Name}} /t:Rebuild /p:Configuration=Release /p:RestorePackagesConfig=True
    - name: 一覧
      run: tree /f
    - name: ビルド結果のアップロード
      uses: actions/upload-artifact@v4
      with:
        name: bin_Release
        path: .\bin\Release


