name: build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest 
    env:
      Solution_Name: volume-utility.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: ビルド(NuGetパッケージ復元あり)
      run: dotnet build ${{env.Solution_Name}} -c Release
    - name: ビルド結果のアップロード
      uses: actions/upload-artifact@v4
      with:
        name: bin_Release
        path: .\bin\Release

    - name: upload
      run: |
        tree /f

